### ISSUE TITLE
Out of date in Opam repository

### ISSUE THREAD

**Issue by milisarge** [xapi-project/xcp-rrd#40]
It seems xcp-rdd package outdated in https://github.com/ocaml/opam-repository/tree/master/packages/xapi-rrd

**Comment by psafont** [comment]
I don't think we're maintaining the packages in the official opam repository, we do it for the [xs-opam](https://github.com/xapi-project/xs-opam) repository

**Comment by mseri** [comment]
We had kept rrd in opam because it was of general interest. We used to make a release every xenserver release. The last one was https://github.com/ocaml/opam-repository/pull/11197

**Comment by mseri** [comment]
A subset of the history of the changes is here:
https://github.com/ocaml/opam-repository/pull/9523
https://github.com/ocaml/opam-repository/pull/9419
https://github.com/ocaml/opam-repository/pull/9206

**Comment by edwintorok** [comment]
It would be good to get at least the OCaml XAPI client into opam again, that should change fairly infrequently (once a release), and should be something useful if someone wants to integrate with XS (ideally it would be part of our SDK).
Perhaps the next time we do an update *from* opam, we can also look at what we can update *to* opam based on the 8.1 release that we just did, with appropriate version constraints (I think we need 4.07.x now?).

**Comment by psafont** [comment]
The package is now being released again to opam-repository, the latest version being 1.9.0
