### ISSUE TITLE
BUG: Failed to build xcp-rrd from master branch

### ISSUE THREAD

**Issue by Yann-Kaelig** [xapi-project/xcp-rrd#46]
Building xcp-rrd from master branch failed with:

> File "lib/rrd.ml", line 61, characters 4-17:
> 61 | let cf_init_value = function
>          ^^^^^^^^^^^^^
> Error (warning 32): unused value cf_init_value.
> File "lib/rrd.ml", line 436, characters 32-33:
> 436 |      rrd_rras = Array.mapi (fun i rra ->
>                                       ^
> Error (warning 27): unused variable i.

[xapi-rdd.log](https://github.com/xapi-project/xcp-rrd/files/4937580/xapi-rdd.log)

**Comment by psafont** [comment]
This error can be omitted by running `dune build @install --profile=release` or `make build`

**Comment by Yann-Kaelig** [comment]
Hi psafont

dune build @install --profile=release fix the issue.

Thx
